services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PORT: 5432
            POSTGRES_PASSWORD: example
            POSTGRES_USER: postgres
            POSTGRES_DB: MOTOR_INSURANCE_WEBSITE
        volumes:
            - pgdata:/var/lib/postgresql/data

    api:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    pgdata:
